name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Prettier check
        run: npm run format:check

      - name: TypeScript typecheck
        run: npm run typecheck

      - name: Run tests
        run: npm run test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: (success() || failure()) && env.ACT != 'true' # always run even if the previous step fails, but skip in local 'act'
        with:
          report_paths: '**/test-results/junit.xml'
